import React from 'react';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import Bank from './Bank';

// Mock the data.json file - we mock data in the tests because technically, they cannot be generated by the render function alone
jest.mock('../../assets/data.json', () => [
  {
    "id": 0,
    "name": "john",
    "balance": 50000
  },
  {
    "id": 1,
    "name": "anne",
    "balance": 40000
  }, 
  {
    "id": 2,
    "name": "elle",
    "balance": 60000
  }
]);

describe('Bank Component', () => {
  describe('Transfer Money - Successful Transaction', () => {
    test('should successfully transfer money between valid users', async () => {
      // Render the Bank component
      render(<Bank />);
      
    });
  });
});
